services:
  node:
    image: "node:19-bullseye"
    user: "node"
    working_dir: /home/node/app
    environment:
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      REDIRECT_URI: ${REDIRECT_URI}
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:8080"
    command: sh -c "yarn && yarn build && yarn start"
